<?php

namespace App\Filament\Pages\RepFamily;

use App\Livewire\FamilyWidget\BloodWidget;
use App\Livewire\FamilyWidget\FaMoGoodWidget;
use App\Livewire\FamilyWidget\FaMoWidget;
use App\Livewire\FamilyWidget\FatherMotherWidget;
use Filament\Pages\Page;

class FatherMother extends Page
{
    protected string $view = 'filament.pages.rep-family.father-mother';
    protected ?string $heading='الأب والأم';

    public function getFooterWidgetsColumns(): int|array
    {
        return 4; // TODO: Change the autogenerated stub
    }

    protected function getFooterWidgets(): array
    {
        return [

            FaMoWidget::class,
            FaMoGoodWidget::class,
            BloodWidget::class,
        ];
    }
}
